FROM apache/airflow:2.7.1

USER root

# Устанавливаем системную либу libgomp1
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libgomp1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

# Устанавливаем всё необходимое для ML сразу в образ
# Используем те версии, которые мы проверили в ходе отладки
RUN pip install --no-cache-dir \
    "joblib<1.4.0" \
    scipy \
    pycaret \
    mlflow \
    pandas \
    lightgbm \
    xgboost \
    catboost